### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by thegimliboy** [yanniks/ghome-fhem#3]
Also, ich glaube ich habe irgendwo etwas falsch gemacht. Also, in meiner Home App versuche ich meinen [test] Dienst hinzu zufügen. Dann werde ich zu einer Seite auf meinem Server weitergeleitet auf der "Link your FHEM devices to Google assistant" steht, da gebe ich nun meine Gmail-Adresse und Passwort ein. Soweit so gut. Dann klicke ich auf Login und erhalte folgende Fehlermeldung:

```
Error: No default engine was specified and no extension was provided.
    at new View (/root/.ghome/node_modules/express/lib/view.js:61:11)
    at EventEmitter.render (/root/.ghome/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/root/.ghome/node_modules/express/lib/response.js:1008:7)
    at login (/root/.ghome/lib/auth-provider.js:389:16)
    at /root/.ghome/lib/auth-provider.js:210:20
    at Layer.handle [as handle_request] (/root/.ghome/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/.ghome/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/root/.ghome/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/root/.ghome/node_modules/express/lib/router/layer.js:95:5)
    at /root/.ghome/node_modules/express/lib/router/index.js:281:22
```

Nun meine Frage: Was mache ich falsch? Schonmal danke im voraus, und danke für dieses Projekt, es scheint ja auch zu funktionieren, wenn man nicht irgendwas vermurkst wie ich.

**Comment by thegimliboy** [comment]
Ok. Also anscheinend muss ich mich doch nicht mit meinen Google Daten anmelden, sondern mit den in der config.json angegebenen. (https://forum.fhem.de/index.php/topic,81557.msg755540.html#msg755540 Erklärt wie ich das meine). Da bin ich selber nicht drauf gekommen.
