### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by StefanRu1** [yanniks/ghome-fhem#6]
Hi,

i hope you can help me. I installed as mentioned in the readme.
When i start ./bin/ghome i get the error below in server.js:1578.
I checked nodejs versions:
node -v : v4.8.0
nodejs -v : v6.14.1

Alexa-fhem is running on my system without problems.

Code: [Auswählen]
fhem@raspberrypi:~/ghome-fhem$ ./bin/ghome
/opt/fhem/ghome-fhem/lib/server.js:1578
                    responses.push(...handleControlOnOff.bind(this)(cmd, exec.params.on ? 1 : 0));
                                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/fhem/ghome-fhem/lib/cli.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

Thanks.
Stefan

**Comment by yanniks** [comment]
Hi Stefan,
by default, the script looks for an executable called `node`. Since release 4.8.0 is already a little bit older (the current LTS release is v8.11.1), please try replacing `#!/usr/bin/env node` inside `bin/ghome` with `#!/usr/bin/env nodejs`. Let's hope that release 6.14.1 is recent enough. :-)

**Comment by StefanRu1** [comment]
Hi,

I installed the newest stable version of node with n (curl -L https://git.io/n-install | bash) and now the ./bin/ghome is starting.

Thank you very much for your help!
